#version: '3.9'

services:
  java_app:
    container_name: java_app
    image: pro-java-app:1.0.0
    build: .
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres